// Generated by CoffeeScript 1.10.0
(function() {
  var insertFunc;

  console.log('inserted...');

  insertFunc = function(data, textStatus) {
    var Preview, latexCode;
    MathJax.Hub.Config({
      showProcessingMessages: false,
      tex2jax: {
        inlineMath: [['$', '$'], ['\\(', '\\)'], ["[math]", "[/math]"]]
      }
    });
    latexCode = null;
    Preview = {
      preview: null,
      buffer: null,
      mjRunning: false,
      oldText: null,
      Init: function() {
        this.preview = document.getElementById("MathPreview");
        return this.buffer = document.getElementById("MathBuffer");
      },
      SwapBuffers: function() {
        var buffer, preview;
        buffer = this.preview;
        preview = this.buffer;
        this.buffer = buffer;
        this.preview = preview;
        buffer.style.visibility = "hidden";
        return preview.style.visibility = "";
      },
      CreatePreview: function() {
        if (this.mjRunning || !latexCode || latexCode === this.oldText) {
          return;
        }
        this.buffer.innerHTML = this.oldText = latexCode;
        this.mjRunning = true;
        return MathJax.Hub.Queue(["Typeset", MathJax.Hub, this.buffer], ["PreviewDone", this]);
      },
      PreviewDone: function() {
        this.mjRunning = false;
        return this.SwapBuffers();
      }
    };
    Preview.callback = MathJax.Callback(["CreatePreview", Preview]);
    Preview.callback.autoReset = true;
    Preview.Init();
    return window.addEventListener("message", function(event) {
      if (event.data.type === 'update') {
        latexCode = '$' + event.data.code + '$';
        console.log('update:', latexCode);
        return Preview.callback();
      }
    });
  };

  if (window.MathJax == null) {
    $.getScript("https://cdn.mathjax.org/mathjax/2.6-latest/MathJax.js?config=TeX-AMS_HTML,Safe").done(insertFunc);
  } else {
    insertFunc();
  }

}).call(this);
